export interface CountryCode {
  code: string;
  flag: string;
  name: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  // Greece first
  { code: '+30',  flag: '🇬🇷', name: 'Greece' },
  // Europe
  { code: '+355', flag: '🇦🇱', name: 'Albania' },
  { code: '+376', flag: '🇦🇩', name: 'Andorra' },
  { code: '+43',  flag: '🇦🇹', name: 'Austria' },
  { code: '+32',  flag: '🇧🇪', name: 'Belgium' },
  { code: '+387', flag: '🇧🇦', name: 'Bosnia' },
  { code: '+359', flag: '🇧🇬', name: 'Bulgaria' },
  { code: '+385', flag: '🇭🇷', name: 'Croatia' },
  { code: '+357', flag: '🇨🇾', name: 'Cyprus' },
  { code: '+420', flag: '🇨🇿', name: 'Czech Republic' },
  { code: '+45',  flag: '🇩🇰', name: 'Denmark' },
  { code: '+372', flag: '🇪🇪', name: 'Estonia' },
  { code: '+358', flag: '🇫🇮', name: 'Finland' },
  { code: '+33',  flag: '🇫🇷', name: 'France' },
  { code: '+49',  flag: '🇩🇪', name: 'Germany' },
  { code: '+36',  flag: '🇭🇺', name: 'Hungary' },
  { code: '+354', flag: '🇮🇸', name: 'Iceland' },
  { code: '+353', flag: '🇮🇪', name: 'Ireland' },
  { code: '+39',  flag: '🇮🇹', name: 'Italy' },
  { code: '+371', flag: '🇱🇻', name: 'Latvia' },
  { code: '+370', flag: '🇱🇹', name: 'Lithuania' },
  { code: '+352', flag: '🇱🇺', name: 'Luxembourg' },
  { code: '+356', flag: '🇲🇹', name: 'Malta' },
  { code: '+373', flag: '🇲🇩', name: 'Moldova' },
  { code: '+377', flag: '🇲🇨', name: 'Monaco' },
  { code: '+382', flag: '🇲🇪', name: 'Montenegro' },
  { code: '+31',  flag: '🇳🇱', name: 'Netherlands' },
  { code: '+389', flag: '🇲🇰', name: 'N. Macedonia' },
  { code: '+47',  flag: '🇳🇴', name: 'Norway' },
  { code: '+48',  flag: '🇵🇱', name: 'Poland' },
  { code: '+351', flag: '🇵🇹', name: 'Portugal' },
  { code: '+40',  flag: '🇷🇴', name: 'Romania' },
  { code: '+7',   flag: '🇷🇺', name: 'Russia' },
  { code: '+381', flag: '🇷🇸', name: 'Serbia' },
  { code: '+421', flag: '🇸🇰', name: 'Slovakia' },
  { code: '+386', flag: '🇸🇮', name: 'Slovenia' },
  { code: '+34',  flag: '🇪🇸', name: 'Spain' },
  { code: '+46',  flag: '🇸🇪', name: 'Sweden' },
  { code: '+41',  flag: '🇨🇭', name: 'Switzerland' },
  { code: '+90',  flag: '🇹🇷', name: 'Turkey' },
  { code: '+380', flag: '🇺🇦', name: 'Ukraine' },
  { code: '+44',  flag: '🇬🇧', name: 'United Kingdom' },
  // Common international
  { code: '+1',   flag: '🇺🇸', name: 'United States' },
  { code: '+1',   flag: '🇨🇦', name: 'Canada' },
  { code: '+61',  flag: '🇦🇺', name: 'Australia' },
  { code: '+55',  flag: '🇧🇷', name: 'Brazil' },
  { code: '+86',  flag: '🇨🇳', name: 'China' },
  { code: '+20',  flag: '🇪🇬', name: 'Egypt' },
  { code: '+972', flag: '🇮🇱', name: 'Israel' },
  { code: '+81',  flag: '🇯🇵', name: 'Japan' },
  { code: '+52',  flag: '🇲🇽', name: 'Mexico' },
  { code: '+212', flag: '🇲🇦', name: 'Morocco' },
  { code: '+64',  flag: '🇳🇿', name: 'New Zealand' },
  { code: '+966', flag: '🇸🇦', name: 'Saudi Arabia' },
  { code: '+27',  flag: '🇿🇦', name: 'South Africa' },
  { code: '+82',  flag: '🇰🇷', name: 'South Korea' },
  { code: '+971', flag: '🇦🇪', name: 'UAE' },
];
